### ISSUE TITLE
Dataset Leul78/qanda not found error

### ISSUE THREAD

**Issue by riimak** [Leulassaminew/finetune-llama-13-b-chat#1]
When trying to run finetune.py I get the error:

`Traceback (most recent call last):
  File "/home/barrage/finetune-llama-13-b-chat/finetune.py", line 58, in <module>
    dataset = load_dataset("Leul78/qanda")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barrage/anaconda3/envs/finetune2/lib/python3.11/site-packages/datasets/load.py", line 2523, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/barrage/anaconda3/envs/finetune2/lib/python3.11/site-packages/datasets/load.py", line 2195, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barrage/anaconda3/envs/finetune2/lib/python3.11/site-packages/datasets/load.py", line 1840, in dataset_module_factory
    raise e1 from None                                         
  File "/home/barrage/anaconda3/envs/finetune2/lib/python3.11/site-packages/datasets/load.py", line 1787, in dataset_module_factory
    raise DatasetNotFoundError(
datasets.exceptions.DatasetNotFoundError: Dataset 'Leul78/qanda' doesn't exist on the Hub. If the repo is private or gated, make sure to log in with `huggingface-cli login`.`

Changing the dataset name from Leul78/qanda to Leul78/fina or Leul78/sales does not help.

Please advise.

**Comment by Leulassaminew** [comment]
Hey, 
Its because the datasets are gated and private which means u need an access token from the account.  If you want to use your own dataset you can create a dataset on hugging face and use it by passing the name of the repository.
